### ISSUE TITLE
Where is "EASYLUA" for Basewars Gamemode?

### ISSUE THREAD

**Issue by Certurix** [CapsAdmin/fast_addons#3]
Hello.
I'm writing an issue right now, because it seems "EASYLUA" has been deleted from this repo.
I need it currently to use it in the basewars Gamemode in Garry's Mod.
Could you upload it or send it?
Thanks.

**Comment by CapsAdmin** [comment]
it sounds a bit strange that you need it in a gamemode, why?

it's here now https://github.com/PAC3-Server/notagain/blob/master/lua/notagain/essential/libraries/easylua.lua

**Comment by Certurix** [comment]
I don't know, in the README file, its says I need easylua.
Thanks you a lot for sharing me the link !
